### ISSUE TITLE
Danku option error

### ISSUE THREAD

**Issue by ByungjunKim** [KoichiYasuoka/SuPar-Kanbun#1]
Hello, Prof. Koichi Yasuoka.

I want to add Danku parameter(True), however I encounter the error below.

"nlp_d('孟子見梁惠王. 王曰,叟! 不遠千里而來, 亦將有以利吾國乎?')"

IndexError                                Traceback (most recent call last)
<ipython-input-9-f70e8da80541> in <module>()
----> 1 nlp_d('孟子見梁惠王. 王曰,叟! 不遠千里而來, 亦將有以利吾國乎?')

2 frames
/usr/local/lib/python3.7/dist-packages/suparkanbun/suparkanbun.py in __call__(self, text)
    111         j=t[i]
    112         k=tradify[j] if j in tradify else j
--> 113         v.append({"form":j,"lemma":k,"pos":p[i][1],"head":h,"deprel":d})
    114         i+=1
    115       for j in reversed(range(0,len(v)-1)):

IndexError: list index out of range

I think that some list variables have problems.

**Comment by KoichiYasuoka** [comment]
Well @ByungjunKim classical Chinese texts do not have punctuations, so you need not include them:

```py
>>> import suparkanbun
>>> nlp=suparkanbun.load(Danku=True)
>>> doc=nlp("孟子見梁惠王王曰叟不遠千里而來亦將有以利吾國乎")
>>> sentences=list(doc.sents)
>>> print(sentences)
[孟子見梁惠王, 王曰, 叟不遠千里而來, 亦將有以利吾國乎]
>>> print(suparkanbun.to_conllu(sentences[2]))
# text = 叟不遠千里而來
1	叟	叟	NOUN	n,名詞,人,人	_	3	nsubj	_	Gloss=old-gentleman|SpaceAfter=No
2	不	不	ADV	v,副詞,否定,無界	_	3	advmod	_	Gloss=not|SpaceAfter=No
3	遠	遠	VERB	v,動詞,描写,量	_	0	root	_	Gloss=distant|SpaceAfter=No
4	千	千	NUM	n,数詞,数字,*	_	3	obj	_	Gloss=thousand|SpaceAfter=No
5	里	里	NOUN	n,名詞,度量衡,*	_	4	clf	_	Gloss=[distance-unit]|SpaceAfter=No
6	而	而	CCONJ	p,助詞,接続,並列	_	7	cc	_	Gloss=and|SpaceAfter=No
7	來	來	VERB	v,動詞,行為,移動	_	3	conj	_	Gloss=come|SpaceAfter=No
```

**Comment by ByungjunKim** [comment]
Thank yor for kind reply.
