### ISSUE TITLE
Punctuation Marker function

### ISSUE THREAD

**Issue by ByungjunKim** [KoichiYasuoka/SuPar-Kanbun#2]
Hello, Prof. Yasuoka.
Is it possible to employ punctuation marker in SuPar-Kanbun?
Danku function is amazing, however I don't know how to use punctuation marker.
For example, there is [Guwen Punc](https://huggingface.co/ethanyt/guwen-punc).
The bottom line is that I want to use Guwen Punc in SuPar-Kanbun.

Thank you.

Regards.
Byungjun Kim.

**Comment by KoichiYasuoka** [comment]
@ByungjunKim it seems very hard task for me, since the labels of ethant/guwen-punc are "," "." "?" "!" "\\" ":" ";" as you can see in its [config.json](https://huggingface.co/ethanyt/guwen-punc/blob/main/config.json). "\\" (backslash)... how do we handle this...

**Comment by ByungjunKim** [comment]
Wow... it is too complicated... 
You're right. It is too hard mission.
