### ISSUE TITLE
No longer using seg.shenshen?

### ISSUE THREAD

**Issue by James-G-Hill** [KoichiYasuoka/SuPar-Kanbun#3]
Hello,

I've looked through the code and it seems that `seg.shenshen` is not being used in this dependency parser (unlike in UD-Kanbun). Is that the case?

I guess this must be the case because the roberta models at least don't segment '君君臣臣父父子子' correctly (the default and large give different segmentations), whereas `seg.shenshen` does. (My interpretation is that this consists of 4 independent statements, each being a 'noun-intransitive verb' phrase.)

**Comment by KoichiYasuoka** [comment]
SuPar-Kanbun uses its own segmentation scheme, which is similar to [roberta-classical-chinese-base-sentence-segmentation](https://huggingface.co/KoichiYasuoka/roberta-classical-chinese-base-sentence-segmentation) from the idea of [王博立](http://xbna.pku.edu.cn/CN/10.13209/j.0479-8023.2017.032). I used [李绅](http://jcip.cipsc.org.cn/CN/Y2021/V35/I4/8)'s `seg.shenshen.wiki` for UD-Kanbun, but [古詩文斷句](https://seg.shenshen.wiki/) was often unstable...

**Comment by James-G-Hill** [comment]
Thanks for pointing me to further resources.
