### ISSUE TITLE
Can I use this model to get embeddings of a paragraph of classical Chinese?

### ISSUE THREAD

**Issue by fishfree** [KoichiYasuoka/SuPar-Kanbun#4]
I also notice [this](https://huggingface.co/KoichiYasuoka/roberta-classical-chinese-large-char#:~:text=Character%2Dembeddings%20are%20enhanced%20into%20traditional/simplified%20characters.).
If so, how to make it?

Many thanks!

**Comment by KoichiYasuoka** [comment]
Sorry but you cannot use SuPar-Kanbun models to get embeddings, since they are Biaffine models to get matrices for dependency-parsing.

**Comment by fishfree** [comment]
Thank you! BTW: Do you know which kinds of LLM support generating embeddings?
