### ISSUE TITLE
Would you pls share the xpos / feats annotation protocols/specifications?

### ISSUE THREAD

**Issue by fishfree** [KoichiYasuoka/SuPar-Kanbun#5]
Hello, Prof. Koichi,
I guess this model is trained from the corpora [here](https://corpus.kanji.zinbun.kyoto-u.ac.jp/gitlab/Kanbun/ud-kanbun). Did you incorporate all the copora there? Because I find this model performs better against Pre-Qin classical Chinese than Post-Qin ones.
Of course, the most important question is as the title.

Many thanks!!

**Comment by KoichiYasuoka** [comment]
Hi @fishfree please read our papers below (in Japanese) for the specifications of XPOS and FEATS:
* [Morphological Analysis of Classical Chinese Texts and Its Application](http://id.nii.ac.jp/1001/00185742/)
* [Designing Universal Dependencies for Classical Chinese and Its Application](http://doi.org/10.20729/00216242)

**Comment by fishfree** [comment]
Thank you!
So, did you incorporate all the copora [here](https://corpus.kanji.zinbun.kyoto-u.ac.jp/gitlab/Kanbun/ud-kanbun) besides 四书? Because I find this model performs better against Pre-Qin classical Chinese than Post-Qin ones.

**Comment by KoichiYasuoka** [comment]
@fishfree please scrutinize our [paper](http://doi.org/10.20729/00216242) again.

**Comment by fishfree** [comment]
@KoichiYasuoka Thank you, Prof! Sorry for bothering you~
