### ISSUE TITLE
Does the parameter "Danku" means Named Entity Recognition?

### ISSUE THREAD

**Issue by fishfree** [KoichiYasuoka/SuPar-Kanbun#6]
I guess from [this line of code](https://github.com/KoichiYasuoka/SuPar-Kanbun/blob/84977e8787bc31173403875e6c74bb2e1332f14b/suparkanbun/suparkanbun.py#L59C7-L59C33). Am I right?

**Comment by KoichiYasuoka** [comment]
No @fishfree `Danku` means sentence segmentation as written in [README](https://github.com/KoichiYasuoka/SuPar-Kanbun/blob/main/README.md).
