### ISSUE TITLE
Why the evaluation results of Trankit is different from SuPar-Kanbu?

### ISSUE THREAD

**Issue by fishfree** [KoichiYasuoka/SuPar-Kanbun#7]
The evaluation results of Trankit is [here](https://trankit.readthedocs.io/en/latest/performance.html#:~:text=Classical_Chinese%2DKyoto), as below:
![image](https://github.com/user-attachments/assets/6bc6da86-0f76-4602-8974-0869c33f227e)
However, in you paper:
![image](https://github.com/user-attachments/assets/97bc75a7-861f-429f-8374-b3bf079d65a1)

What are the evaluation critiera and related stuff?

**Comment by KoichiYasuoka** [comment]
@fishfree please scrutinize our [paper](http://doi.org/10.20729/00216242) again and again.【問題文I】 and 【問題文II】 are from 大学入学共通テストの令和3年度本試験『国語』(2021年1月16日実施)第4問の問題文 not from old Universal Dependencies 2.5.
